import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Liwa",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id:'1',
      name: "Apple Airpods",
      slug: "apple airpods",
      category: "Mobile Accessories",
      image: "/images/airpods.jpg", // 679px × 829px
      price: 300,
      countInStock: 10,
      brand: "Apple",
      rating: 4.5,
      numReviews: 10,
      description: "Noise cancelling earphones",
    },
    {
      // _id:'2',
      name: "Alexa",
      slug: "alexa",
      category: "Home",
      image: "/images/alexa.jpg",
      price: 150,
      countInStock: 0,
      brand: "Amazon",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id:'3',
      name: "DSLR Camera",
      slug: "dslr camera",
      category: "tech",
      image: "/images/camera.jpg",
      price: 900,
      countInStock: 3,
      brand: "Nikon",
      rating: 4.5,
      numReviews: 14,
      description: "high quality camera",
    },
    {
      // _id:'4',
      name: "Iphone 14 pro max",
      slug: "iphone 14 pro max",
      category: "Mobile",
      image: "/images/phone.jpg",
      price: 1200,
      countInStock: 5,
      brand: "Apple",
      rating: 4.5,
      numReviews: 10,
      description: "Worlds fastest phone",
    },
    {
      // _id:'5',
      name: "Playstation 4",
      slug: "playstation 4",
      category: "Console",
      image: "/images/playstation.jpg",
      price: 700,
      countInStock: 5,
      brand: "Sony",
      rating: 4.5,
      numReviews: 10,
      description: "Worlds best console",
    },
  ],
};
export default data;
